modLoader="javafml"
loaderVersion="[${forge_major},)"
license="MIT"

[[mods]]
modId="enderban"
version="\${file.jarVersion}"
displayName="EnderBan"
authors="ufhs"
description='''Disables banned items inside Ender Chests.'''

[[dependencies.enderban]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_major},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enderban]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
